"""orcamentos_campos_e_premissa_descricao

Revision ID: 085c2e6077cd
Revises: 83c121c85d03
Create Date: 2026-05-11 03:25:51.820398

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c2e6077cd'
down_revision: Union[str, None] = '83c121c85d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('endereco', sa.Text(), nullable=True))
    op.add_column('orcamentos', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('orcamentos', sa.Column('telefone', sa.String(length=30), nullable=True))
    op.add_column('orcamentos', sa.Column('cpf', sa.String(length=20), nullable=True))
    op.add_column('orcamentos', sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('premissas', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premissas', 'descricao')
    op.drop_column('orcamentos', 'fechado_em')
    op.drop_column('orcamentos', 'cpf')
    op.drop_column('orcamentos', 'telefone')
    op.drop_column('orcamentos', 'email')
    op.drop_column('orcamentos', 'endereco')
    # ### end Alembic commands ###
