"""orcamentos_refactor_e_caixa_os

Revision ID: 0eb73cb851c8
Revises: 1d2247a23a29
Create Date: 2026-05-11 03:37:24.465573

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eb73cb851c8'
down_revision: Union[str, None] = '1d2247a23a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_caixa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_caixa_empresa_id'), 'produtos_caixa', ['empresa_id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sessao_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome_cliente', sa.String(length=200), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=False),
    sa.Column('descricao_servico', sa.Text(), nullable=False),
    sa.Column('valor_servico', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_produtos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_caixa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_criado_em'), 'ordens_servico', ['criado_em'], unique=False)
    op.create_index(op.f('ix_ordens_servico_empresa_id'), 'ordens_servico', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_numero'), 'ordens_servico', ['numero'], unique=False)
    op.create_index(op.f('ix_ordens_servico_sessao_id'), 'ordens_servico', ['sessao_id'], unique=False)
    op.create_table('premissas_orcamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=False),
    sa.Column('premissa_id', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_calculado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['premissa_id'], ['premissas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premissas_orcamento_orcamento_id'), 'premissas_orcamento', ['orcamento_id'], unique=False)
    op.create_table('itens_os',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('os_id', sa.String(length=36), nullable=False),
    sa.Column('produto_id', sa.String(length=36), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_caixa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_os_os_id'), 'itens_os', ['os_id'], unique=False)
    op.drop_index(op.f('ix_vendas_caixa_empresa_id'), table_name='vendas_caixa')
    op.drop_index(op.f('ix_vendas_caixa_sessao_id'), table_name='vendas_caixa')
    op.drop_table('vendas_caixa')
    op.drop_constraint(op.f('itens_orcamento_premissa_id_fkey'), 'itens_orcamento', type_='foreignkey')
    op.drop_column('itens_orcamento', 'percentual')
    op.drop_column('itens_orcamento', 'premissa_id')
    op.drop_column('itens_orcamento', 'valor_manual')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_orcamento', sa.Column('valor_manual', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('itens_orcamento', sa.Column('premissa_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('itens_orcamento', sa.Column('percentual', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('itens_orcamento_premissa_id_fkey'), 'itens_orcamento', 'premissas', ['premissa_id'], ['id'])
    op.create_table('vendas_caixa',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sessao_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('itens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('desconto', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('vendas_caixa_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_caixa.id'], name=op.f('vendas_caixa_sessao_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vendas_caixa_pkey'))
    )
    op.create_index(op.f('ix_vendas_caixa_sessao_id'), 'vendas_caixa', ['sessao_id'], unique=False)
    op.create_index(op.f('ix_vendas_caixa_empresa_id'), 'vendas_caixa', ['empresa_id'], unique=False)
    op.drop_index(op.f('ix_itens_os_os_id'), table_name='itens_os')
    op.drop_table('itens_os')
    op.drop_index(op.f('ix_premissas_orcamento_orcamento_id'), table_name='premissas_orcamento')
    op.drop_table('premissas_orcamento')
    op.drop_index(op.f('ix_ordens_servico_sessao_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_numero'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_empresa_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_criado_em'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_produtos_caixa_empresa_id'), table_name='produtos_caixa')
    op.drop_table('produtos_caixa')
    # ### end Alembic commands ###
