"""estoque_minimo_e_movimentos

Revision ID: 1d2247a23a29
Revises: 085c2e6077cd
Create Date: 2026-05-11 03:30:50.734522

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2247a23a29'
down_revision: Union[str, None] = '085c2e6077cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentos_estoque',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('criado_por', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantidade_anterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantidade_posterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens_estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentos_estoque_criado_em'), 'movimentos_estoque', ['criado_em'], unique=False)
    op.create_index(op.f('ix_movimentos_estoque_empresa_id'), 'movimentos_estoque', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimentos_estoque_item_id'), 'movimentos_estoque', ['item_id'], unique=False)
    op.add_column('itens_estoque', sa.Column('estoque_minimo', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_estoque', 'estoque_minimo')
    op.drop_index(op.f('ix_movimentos_estoque_item_id'), table_name='movimentos_estoque')
    op.drop_index(op.f('ix_movimentos_estoque_empresa_id'), table_name='movimentos_estoque')
    op.drop_index(op.f('ix_movimentos_estoque_criado_em'), table_name='movimentos_estoque')
    op.drop_table('movimentos_estoque')
    # ### end Alembic commands ###
