"""initial

Revision ID: 83c121c85d03
Revises: 
Create Date: 2026-05-11 03:15:33.785110

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c121c85d03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('razao_social', sa.String(length=300), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cor_primaria', sa.String(length=20), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_grupo_id'), 'empresas', ['grupo_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_table('itens_estoque',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_atribuido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_estoque_empresa_id'), 'itens_estoque', ['empresa_id'], unique=False)
    op.create_table('premissas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premissas_empresa_id'), 'premissas', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('permissoes', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_grupo_id'), 'usuarios', ['grupo_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('empresa_lead', sa.String(length=200), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_empresa_id'), 'leads', ['empresa_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('criado_por', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('custo_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_empresa_id'), 'orcamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_numero'), 'orcamentos', ['numero'], unique=True)
    op.create_table('registros_auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=True),
    sa.Column('empresa_id', sa.String(length=36), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('usuario_nome', sa.String(length=200), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('recurso_id', sa.String(length=36), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_auditoria_acao'), 'registros_auditoria', ['acao'], unique=False)
    op.create_index(op.f('ix_registros_auditoria_criado_em'), 'registros_auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_registros_auditoria_empresa_id'), 'registros_auditoria', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_registros_auditoria_grupo_id'), 'registros_auditoria', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_registros_auditoria_recurso'), 'registros_auditoria', ['recurso'], unique=False)
    op.create_index(op.f('ix_registros_auditoria_usuario_id'), 'registros_auditoria', ['usuario_id'], unique=False)
    op.create_table('sessoes_caixa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('operador_id', sa.String(length=36), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aberta', sa.Boolean(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_caixa_empresa_id'), 'sessoes_caixa', ['empresa_id'], unique=False)
    op.create_table('comissoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('orcamento_numero', sa.String(length=20), nullable=True),
    sa.Column('vendedor_id', sa.String(length=36), nullable=False),
    sa.Column('vendedor_nome', sa.String(length=200), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comissoes_empresa_id'), 'comissoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_comissoes_vendedor_id'), 'comissoes', ['vendedor_id'], unique=False)
    op.create_table('itens_orcamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('premissa_id', sa.String(length=36), nullable=True),
    sa.Column('item_estoque_id', sa.String(length=36), nullable=True),
    sa.Column('percentual', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('valor_manual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_calculado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_estoque_id'], ['itens_estoque.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['premissa_id'], ['premissas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_orcamento_orcamento_id'), 'itens_orcamento', ['orcamento_id'], unique=False)
    op.create_table('movimentos_caixa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('criado_por', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentos_caixa_data'), 'movimentos_caixa', ['data'], unique=False)
    op.create_index(op.f('ix_movimentos_caixa_empresa_id'), 'movimentos_caixa', ['empresa_id'], unique=False)
    op.create_table('vendas_caixa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sessao_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('itens', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_caixa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_caixa_empresa_id'), 'vendas_caixa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vendas_caixa_sessao_id'), 'vendas_caixa', ['sessao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_caixa_sessao_id'), table_name='vendas_caixa')
    op.drop_index(op.f('ix_vendas_caixa_empresa_id'), table_name='vendas_caixa')
    op.drop_table('vendas_caixa')
    op.drop_index(op.f('ix_movimentos_caixa_empresa_id'), table_name='movimentos_caixa')
    op.drop_index(op.f('ix_movimentos_caixa_data'), table_name='movimentos_caixa')
    op.drop_table('movimentos_caixa')
    op.drop_index(op.f('ix_itens_orcamento_orcamento_id'), table_name='itens_orcamento')
    op.drop_table('itens_orcamento')
    op.drop_index(op.f('ix_comissoes_vendedor_id'), table_name='comissoes')
    op.drop_index(op.f('ix_comissoes_empresa_id'), table_name='comissoes')
    op.drop_table('comissoes')
    op.drop_index(op.f('ix_sessoes_caixa_empresa_id'), table_name='sessoes_caixa')
    op.drop_table('sessoes_caixa')
    op.drop_index(op.f('ix_registros_auditoria_usuario_id'), table_name='registros_auditoria')
    op.drop_index(op.f('ix_registros_auditoria_recurso'), table_name='registros_auditoria')
    op.drop_index(op.f('ix_registros_auditoria_grupo_id'), table_name='registros_auditoria')
    op.drop_index(op.f('ix_registros_auditoria_empresa_id'), table_name='registros_auditoria')
    op.drop_index(op.f('ix_registros_auditoria_criado_em'), table_name='registros_auditoria')
    op.drop_index(op.f('ix_registros_auditoria_acao'), table_name='registros_auditoria')
    op.drop_table('registros_auditoria')
    op.drop_index(op.f('ix_orcamentos_numero'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_empresa_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_leads_empresa_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_usuarios_grupo_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_premissas_empresa_id'), table_name='premissas')
    op.drop_table('premissas')
    op.drop_index(op.f('ix_itens_estoque_empresa_id'), table_name='itens_estoque')
    op.drop_table('itens_estoque')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_empresas_grupo_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('grupos')
    # ### end Alembic commands ###
