"""vendedor_comissao_contas_categorias

Revision ID: c289bdf9a8c6
Revises: 0eb73cb851c8
Create Date: 2026-05-11 14:34:23.500203

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c289bdf9a8c6'
down_revision: Union[str, None] = '0eb73cb851c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_financeiro',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_financeiro_empresa_id'), 'categorias_financeiro', ['empresa_id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('parceiro', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_data_vencimento'), 'contas', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_empresa_id'), 'contas', ['empresa_id'], unique=False)
    op.add_column('clientes', sa.Column('vendedor_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'clientes', 'usuarios', ['vendedor_id'], ['id'])
    op.add_column('orcamentos', sa.Column('vendedor_id', sa.String(length=36), nullable=True))
    op.add_column('orcamentos', sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'orcamentos', 'usuarios', ['vendedor_id'], ['id'])
    op.add_column('usuarios', sa.Column('comissao_percentual', sa.Numeric(precision=8, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'comissao_percentual')
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.drop_column('orcamentos', 'enviado_em')
    op.drop_column('orcamentos', 'vendedor_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'vendedor_id')
    op.drop_index(op.f('ix_contas_empresa_id'), table_name='contas')
    op.drop_index(op.f('ix_contas_data_vencimento'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_categorias_financeiro_empresa_id'), table_name='categorias_financeiro')
    op.drop_table('categorias_financeiro')
    # ### end Alembic commands ###
